tasks:
  - source: src/visualization/visualize.py
    product:
      nb: notebooks/visualize.ipynb
  - source: src/models/train_model.py
    product:
      nb: notebooks/train_model.ipynb
  - source: src/models/predict_model.py
    product:
      nb: notebooks/predict_model.ipynb